/* ================================================================
   よみときコード 用語マスタ (glossary.js)
   コードブロック内の単語にカーソルをのせると、この辞書を参照して
   解説ツールチップが表示される。

   追加方法: 下の形式で1行足すだけ。
   "単語": {cat:"カテゴリ", desc:"やさしい説明"},

   - キーは大文字小文字を区別する(見つからない場合は小文字でも再検索される)
   - "console.log" のようなドット付きキーもOK
   - "=>" のような記号キーもOK
   ================================================================ */
window.YOMITOKI_GLOSSARY = {

/* ===== JavaScript キーワード ===== */
"let":{cat:"JSキーワード",desc:"後から中身を変えられる変数を宣言する。迷ったらconst、変更が必要なときだけlet。"},
"const":{cat:"JSキーワード",desc:"再代入できない変数を宣言する。「この値は途中で変わらない」と読み手に伝わる。"},
"var":{cat:"JSキーワード",desc:"古い変数宣言。スコープの扱いが緩く事故のもとになるため、今はlet/constを使う。"},
"function":{cat:"JSキーワード",desc:"関数(処理のまとまり)を定義する。functionの後の名前が関数名。"},
"return":{cat:"JSキーワード",desc:"関数の結果(戻り値)を呼び出し元に返して、関数の実行を終える。"},
"if":{cat:"JSキーワード",desc:"「もし〜なら」の条件分岐。( )内の条件がtrueのときだけ{ }内を実行する。"},
"else":{cat:"JSキーワード",desc:"ifの条件が成り立たなかったときに実行する処理を書く。else ifで条件を追加できる。"},
"for":{cat:"JSキーワード",desc:"繰り返し処理(ループ)。for(初期化; 続ける条件; 更新)の3点セットで書く。"},
"while":{cat:"JSキーワード",desc:"条件がtrueの間ずっと繰り返すループ。条件が永遠にtrueだと無限ループになるので注意。"},
"switch":{cat:"JSキーワード",desc:"1つの値を複数のcaseと比べて分岐する。if-else ifが長く並ぶときの代替。"},
"case":{cat:"JSキーワード",desc:"switch文の中の「この値だったら」という分岐先。最後にbreakを忘れると次のcaseまで実行される。"},
"break":{cat:"JSキーワード",desc:"ループやswitchをその場で抜ける。"},
"continue":{cat:"JSキーワード",desc:"ループの今の回だけをスキップして、次の回へ進む。"},
"try":{cat:"JSキーワード",desc:"エラーが起きるかもしれない処理を囲む。エラーが起きたらcatchに飛ぶ。"},
"catch":{cat:"JSキーワード",desc:"tryの中でエラーが起きたときの受け皿。アプリ全体が止まるのを防ぐ。"},
"finally":{cat:"JSキーワード",desc:"エラーが起きても起きなくても、最後に必ず実行される後片付け処理。"},
"throw":{cat:"JSキーワード",desc:"自分でエラーを発生させる。throw new Error(\"メッセージ\") の形が定番。"},
"new":{cat:"JSキーワード",desc:"クラスやコンストラクタから新しいインスタンス(実体)を作る。new Date()など。"},
"class":{cat:"JSキーワード",desc:"オブジェクトの設計図。プロパティ(データ)とメソッド(処理)をまとめて定義する。"},
"extends":{cat:"JSキーワード",desc:"クラスの継承。親クラスの機能を引き継いだ子クラスを作る。"},
"constructor":{cat:"JSキーワード",desc:"クラスからnewでインスタンスを作るときに最初に実行される初期化処理。"},
"super":{cat:"JSキーワード",desc:"子クラスから親クラスのコンストラクタやメソッドを呼び出す。"},
"this":{cat:"JSキーワード",desc:"「今の文脈のオブジェクト自身」を指す。呼び出し方によって中身が変わる、JSの難所のひとつ。"},
"typeof":{cat:"JSキーワード",desc:"値の型を文字列で返す。typeof \"a\" は \"string\"。型の確認やデバッグに使う。"},
"instanceof":{cat:"JSキーワード",desc:"あるオブジェクトが特定のクラスから作られたかを判定する。"},
"in":{cat:"JSキーワード",desc:"「キーがオブジェクトに存在するか」の判定や、for...inループで使う。"},
"of":{cat:"JSキーワード",desc:"for...ofの形で、配列などの中身を1つずつ取り出すループに使う。"},
"delete":{cat:"JSキーワード",desc:"オブジェクトからプロパティを削除する。"},
"yield":{cat:"JSキーワード",desc:"ジェネレーター関数で値を1つずつ返しては一時停止する。上級者向けの機能。"},
"async":{cat:"JS非同期",desc:"「この関数の中でawaitを使います」という宣言。async関数は常にPromiseを返す。"},
"await":{cat:"JS非同期",desc:"非同期処理(fetchなど)が終わるまで待つ印。付け忘れるとPromiseオブジェクトが返ってきてバグる定番ポイント。"},
"import":{cat:"JSキーワード",desc:"他のファイル(モジュール)から関数や変数を読み込む。"},
"export":{cat:"JSキーワード",desc:"他のファイルから使えるように関数や変数を公開する。"},
"default":{cat:"JSキーワード",desc:"export defaultでモジュールの代表を1つ公開する。switch文では「どのcaseにも当てはまらないとき」。"},
"static":{cat:"JSキーワード",desc:"インスタンスを作らずクラス名から直接呼べるメソッド/プロパティ。Math.random()のような形。"},
"null":{cat:"JS基礎",desc:"「意図的に空」を表す値。undefinedと違い、開発者が意図して入れる空。"},
"undefined":{cat:"JS基礎",desc:"「未定義」。値がまだ入っていない変数や、存在しないプロパティを参照すると出てくる。"},
"true":{cat:"JS基礎",desc:"真偽値の「真(はい)」。条件分岐の判定に使われる。"},
"false":{cat:"JS基礎",desc:"真偽値の「偽(いいえ)」。"},
"NaN":{cat:"JS基礎",desc:"Not a Number(数値じゃない)。数値にできない計算の結果。NaN === NaN もfalseになる曲者。"},
"Infinity":{cat:"JS基礎",desc:"無限大を表す特別な数値。1/0の結果など。"},

/* ===== JavaScript 基礎・概念 ===== */
"変数":{cat:"概念",desc:"値を入れておく箱に名前をつけたもの。JSではlet/constで宣言する。"},
"引数":{cat:"概念",desc:"関数に渡す値。「ひきすう」と読む。関数定義側の受け取り名は仮引数とも呼ぶ。"},
"戻り値":{cat:"概念",desc:"関数がreturnで返す結果の値。"},
"callback":{cat:"JS基礎",desc:"コールバック関数。「あとで呼び出してもらう」ために他の関数へ渡す関数。イベントや配列メソッドで頻出。"},
"コールバック":{cat:"JS基礎",desc:"「あとで呼び出してもらう」ために他の関数へ渡す関数。addEventListenerの第2引数などが典型。"},
"closure":{cat:"JS基礎",desc:"クロージャ。関数が「自分が作られた場所の変数」を覚え続ける仕組み。カウンターの実装などで登場。"},
"scope":{cat:"JS基礎",desc:"スコープ。変数が見える範囲のこと。{ }の中で宣言した変数は基本その中でしか使えない。"},
"hoisting":{cat:"JS基礎",desc:"巻き上げ。varやfunction宣言がコードの先頭に持ち上げられたように動く仕様。varの事故原因。"},
"template":{cat:"JS基礎",desc:"テンプレート文字列。バッククォートで囲み、${変数}で文字列に値を埋め込める。"},
"destructuring":{cat:"JS基礎",desc:"分割代入。const {name, age} = user; のようにオブジェクトや配列から一気に取り出す書き方。"},
"spread":{cat:"JS基礎",desc:"スプレッド構文(...)。配列やオブジェクトの中身を展開する。[...arr]でコピーが作れる。"},
"strict":{cat:"JS基礎",desc:"\"use strict\"(厳格モード)。曖昧な書き方をエラーにして事故を防ぐ宣言。"},
"undefined vs null":{cat:"JS基礎",desc:"undefinedは「まだ何も入っていない」、nullは「意図的に空にした」。"},
"boolean":{cat:"JS基礎",desc:"真偽値。true(真)かfalse(偽)の2択のデータ型。条件分岐の材料になる。"},
"string":{cat:"JS基礎",desc:"文字列型。引用符(\" ' `)で囲まれたテキストデータ。\"3\"は数値ではなく文字。"},
"number":{cat:"JS基礎",desc:"数値型。JSでは整数も小数も同じnumber型。0.1+0.2が0.30000...4になる誤差に注意。"},
"array":{cat:"JS基礎",desc:"配列。順番に並んだデータのリスト。0番から数える。[1, 2, 3]の形。"},
"object":{cat:"JS基礎",desc:"オブジェクト。キー(名前)と値のペアの集まり。{name: \"太郎\", age: 6}の形。"},
"Object":{cat:"JS組み込み",desc:"オブジェクト操作の道具箱。Object.keys/values/entriesでキーや値を配列として取り出せる。"},
"Symbol":{cat:"JS組み込み",desc:"必ず一意になる特別な値を作る型。ライブラリ内部などで使われる上級者向け機能。"},
"Map":{cat:"JS組み込み",desc:"キーと値のペアを保持するコレクション。オブジェクトと違い、どんな型もキーにできて順序も保たれる。"},
"Set":{cat:"JS組み込み",desc:"重複しない値の集まり。[...new Set(arr)]で配列の重複除去ができる定番技。"},
"Date":{cat:"JS組み込み",desc:"日時を扱うオブジェクト。new Date()で現在日時。月が0始まり(0=1月)なのが有名な罠。"},
"RegExp":{cat:"JS組み込み",desc:"正規表現。文字列のパターン検索・置換に使う。/\\d+/ のようにスラッシュで囲んで書く。"},
"Error":{cat:"JS組み込み",desc:"エラーオブジェクト。new Error(\"説明\")で作り、throwで投げ、catchで受け止める。"},
"Proxy":{cat:"JS組み込み",desc:"オブジェクトへの読み書きに割り込んで独自処理を挟める仕組み。VueなどのフレームワークがUI自動更新に利用。"},

/* ===== 配列メソッド ===== */
"map":{cat:"配列",desc:"配列の全要素を変換して新しい配列を作る。arr.map(x => x * 2)で全要素2倍。元の配列は変わらない。"},
"filter":{cat:"配列",desc:"条件に合う要素だけを集めた新しい配列を作る。arr.filter(x => x > 10)など。"},
"reduce":{cat:"配列",desc:"配列を1つの値に畳み込む。合計や集計に使う。arr.reduce((sum, x) => sum + x, 0)で合計。"},
"forEach":{cat:"配列",desc:"配列の全要素に対して処理を実行する。mapと違い新しい配列は返さない。"},
"find":{cat:"配列",desc:"条件に合う最初の要素を1つ返す。見つからなければundefined。"},
"findIndex":{cat:"配列",desc:"条件に合う最初の要素の位置(番号)を返す。見つからなければ-1。"},
"some":{cat:"配列",desc:"条件に合う要素が1つでもあればtrue。「どれか該当する?」の判定。"},
"every":{cat:"配列",desc:"全要素が条件に合えばtrue。「全部該当する?」の判定。"},
"push":{cat:"配列",desc:"配列の末尾に要素を追加する。元の配列を直接変更する。"},
"pop":{cat:"配列",desc:"配列の末尾の要素を取り除いて返す。"},
"shift":{cat:"配列",desc:"配列の先頭の要素を取り除いて返す。"},
"unshift":{cat:"配列",desc:"配列の先頭に要素を追加する。"},
"splice":{cat:"配列",desc:"配列の途中の要素を削除・追加・置換する。元の配列を直接変更するので注意。"},
"slice":{cat:"配列/文字列",desc:"一部を切り出して新しい配列/文字列を返す。slice(1, 3)で1番目から3番目の手前まで。元は変わらない。"},
"concat":{cat:"配列",desc:"配列同士をつなげた新しい配列を返す。今は[...a, ...b]のスプレッド構文も定番。"},
"sort":{cat:"配列",desc:"配列を並び替える。数値は sort((a,b) => a-b) のように比較関数が必要。元の配列を直接変更する。"},
"reverse":{cat:"配列",desc:"配列の順序を逆にする。元の配列を直接変更する。"},
"flat":{cat:"配列",desc:"入れ子の配列を平らにする。[[1,2],[3]].flat() → [1,2,3]。"},
"includes":{cat:"配列/文字列",desc:"指定した値が含まれているかをtrue/falseで返す。"},
"indexOf":{cat:"配列/文字列",desc:"指定した値が最初に見つかる位置を返す。見つからなければ-1。"},
"join":{cat:"配列",desc:"配列の要素をつなげて1つの文字列にする。[\"a\",\"b\"].join(\"-\") → \"a-b\"。"},
"length":{cat:"配列/文字列",desc:"配列の要素数、または文字列の文字数。最後の要素はarr[arr.length - 1]。"},
"Array.isArray":{cat:"配列",desc:"値が配列かどうかを判定する。typeofでは配列も\"object\"になるのでこちらを使う。"},
"Array.from":{cat:"配列",desc:"配列っぽいもの(NodeListなど)を本物の配列に変換する。querySelectorAllの結果に配列メソッドを使いたいときに。"},

/* ===== 文字列メソッド ===== */
"split":{cat:"文字列",desc:"文字列を区切り文字で分割して配列にする。\"a,b,c\".split(\",\") → [\"a\",\"b\",\"c\"]。"},
"replace":{cat:"文字列",desc:"文字列の一部を置き換える。最初の1件だけ。全部置換はreplaceAllか正規表現のgフラグ。"},
"replaceAll":{cat:"文字列",desc:"一致する箇所をすべて置き換える。"},
"trim":{cat:"文字列",desc:"文字列の前後の空白・改行を取り除く。入力チェックの前処理でよく使う。"},
"toUpperCase":{cat:"文字列",desc:"文字列をすべて大文字にする。"},
"toLowerCase":{cat:"文字列",desc:"文字列をすべて小文字にする。検索の大文字小文字を無視したいときの定番。"},
"startsWith":{cat:"文字列",desc:"文字列が指定の文字で始まるかをtrue/falseで返す。"},
"endsWith":{cat:"文字列",desc:"文字列が指定の文字で終わるかをtrue/falseで返す。"},
"padStart":{cat:"文字列",desc:"指定の長さになるまで先頭に文字を埋める。\"5\".padStart(2,\"0\") → \"05\"。時刻表示で定番。"},
"charAt":{cat:"文字列",desc:"指定位置の1文字を返す。str[0]のような書き方でも同じ。"},
"substring":{cat:"文字列",desc:"文字列の一部を切り出す。ほぼsliceと同じ(負の数の扱いが違う)。"},
"match":{cat:"文字列",desc:"正規表現でパターンに一致する部分を探して返す。"},
"test":{cat:"正規表現",desc:"正規表現が文字列に一致するかをtrue/falseで返す。/\\d/.test(\"a1\") → true。"},
"toString":{cat:"JS基礎",desc:"値を文字列に変換する。(255).toString(16)で16進数文字列にもできる。"},
"toFixed":{cat:"数値",desc:"小数点以下の桁数を固定した文字列にする。(3.14159).toFixed(2) → \"3.14\"。"},

/* ===== 数値・Math・JSON ===== */
"Math.random":{cat:"数値",desc:"0以上1未満のランダムな小数を返す。Math.floor(Math.random() * 6) + 1 でサイコロ。"},
"Math.floor":{cat:"数値",desc:"小数点以下を切り捨てる。Math.floor(3.9) → 3。"},
"Math.ceil":{cat:"数値",desc:"小数点以下を切り上げる。Math.ceil(3.1) → 4。"},
"Math.round":{cat:"数値",desc:"四捨五入する。Math.round(3.5) → 4。"},
"Math.max":{cat:"数値",desc:"渡した値の中で最大のものを返す。配列にはMath.max(...arr)とスプレッドで。"},
"Math.min":{cat:"数値",desc:"渡した値の中で最小のものを返す。"},
"Math.abs":{cat:"数値",desc:"絶対値(マイナスを取った値)を返す。"},
"Math":{cat:"JS組み込み",desc:"数学系の道具箱。random(乱数)、floor(切り捨て)、round(四捨五入)などをまとめて持つ。"},
"parseInt":{cat:"数値",desc:"文字列を整数に変換する。parseInt(\"42px\") → 42。基数を第2引数で指定するのが安全: parseInt(s, 10)。"},
"parseFloat":{cat:"数値",desc:"文字列を小数に変換する。"},
"Number":{cat:"数値",desc:"値を数値に変換する。Number(\"3\") → 3。変換できないとNaNになる。"},
"Number.isNaN":{cat:"数値",desc:"値がNaNかどうかを正確に判定する。NaN === NaN がfalseなので、この関数を使う。"},
"isNaN":{cat:"数値",desc:"数値にできない値かを判定する。文字列も暗黙変換されるため、より厳密なNumber.isNaNが推奨。"},
"JSON.parse":{cat:"JSON",desc:"JSON文字列をJavaScriptのオブジェクトに変換する。壊れたJSONだと例外を投げるのでtry/catchとセットで。"},
"JSON.stringify":{cat:"JSON",desc:"オブジェクトをJSON文字列に変換する。保存や送信の前に使う。parseと方向を間違えるのが定番ミス。"},
"JSON":{cat:"JSON",desc:"データ交換の共通フォーマット。JS由来だが、今やあらゆる言語・APIの共通語。{\"key\": \"value\"}の形。"},

/* ===== 非同期・Promise ===== */
"Promise":{cat:"JS非同期",desc:"「あとで結果が届く」ことを表すオブジェクト。awaitを付け忘れると結果でなくこれが返ってくる。"},
"then":{cat:"JS非同期",desc:"Promiseの結果が届いたら実行する処理をつなぐ。今はasync/awaitで書くのが主流。"},
"Promise.all":{cat:"JS非同期",desc:"複数の非同期処理を並行実行し、全部終わるのを待つ。1つでも失敗すると全体が失敗扱い。"},
"Promise.race":{cat:"JS非同期",desc:"複数の非同期処理のうち、最初に決着したものの結果を採用する。"},
"resolve":{cat:"JS非同期",desc:"Promiseを成功で完了させる。Promise.resolve(値)は「即成功のPromise」を作る。"},
"reject":{cat:"JS非同期",desc:"Promiseを失敗で完了させる。catchで受け止める側とセット。"},
"setTimeout":{cat:"JS非同期",desc:"指定ミリ秒後に1回だけ処理を実行する。setTimeout(fn, 1000)で1秒後。"},
"setInterval":{cat:"JS非同期",desc:"指定ミリ秒ごとに処理を繰り返す。clearIntervalで止めないと動き続けるので注意。"},
"clearTimeout":{cat:"JS非同期",desc:"setTimeoutで予約した処理をキャンセルする。"},
"clearInterval":{cat:"JS非同期",desc:"setIntervalの繰り返しを停止する。"},
"requestAnimationFrame":{cat:"JS非同期",desc:"ブラウザの描画タイミング(約60回/秒)に合わせて処理を実行する。アニメーションの定番。"},
"event loop":{cat:"概念",desc:"イベントループ。JSが「今の処理が終わったら次のタスクを実行する」を回し続ける仕組み。非同期の土台。"},

/* ===== DOM・ブラウザ ===== */
"document":{cat:"DOM",desc:"ページ全体を表すオブジェクト。HTMLの要素を探したり作ったりする入口。"},
"getElementById":{cat:"DOM",desc:"id属性で要素を1つ取得する。document.getElementById(\"title\")。DOM操作の基本中の基本。"},
"querySelector":{cat:"DOM",desc:"CSSセレクタで要素を1つ取得する。\"#id\"、\".class\"、\"div > p\"など柔軟に指定できる。"},
"querySelectorAll":{cat:"DOM",desc:"CSSセレクタに一致する要素を全部取得する。結果はNodeList(配列もどき)。forEachは使える。"},
"addEventListener":{cat:"DOM",desc:"要素にイベント(クリック等)への反応を登録する。addEventListener(\"click\", 関数)の形。アプリの動きの起点。"},
"removeEventListener":{cat:"DOM",desc:"登録したイベントリスナーを解除する。登録時と同じ関数参照を渡す必要がある。"},
"textContent":{cat:"DOM",desc:"要素の表示テキストを読み書きする。中身をただの文字として扱うのでXSSの心配がない安全な書き方。"},
"innerHTML":{cat:"DOM",desc:"要素の中身をHTMLとして読み書きする。ユーザー入力をそのまま入れるとXSSの入口になるので要注意。"},
"innerText":{cat:"DOM",desc:"表示されているテキストを読み書きする。textContentと似ているが、非表示要素の扱いなどが違う。"},
"createElement":{cat:"DOM",desc:"新しいHTML要素を作る。document.createElement(\"div\")。appendChildでページに追加して初めて表示される。"},
"appendChild":{cat:"DOM",desc:"要素の子として別の要素を追加する。"},
"append":{cat:"DOM",desc:"要素の末尾に要素や文字列を追加する。appendChildより柔軟な新しめのメソッド。"},
"removeChild":{cat:"DOM",desc:"子要素を削除する。今は要素自身の remove() でも消せる。"},
"remove":{cat:"DOM",desc:"要素を自分自身でページから削除する。el.remove()。"},
"classList":{cat:"DOM",desc:"要素のclass属性を操作する。add/remove/toggle/containsで付け外しと判定ができる。"},
"toggle":{cat:"DOM",desc:"classList.toggle(\"open\")のように、クラスがあれば外し、なければ付ける。開閉UIの定番。"},
"setAttribute":{cat:"DOM",desc:"要素の属性を設定する。el.setAttribute(\"src\", \"a.png\")。"},
"getAttribute":{cat:"DOM",desc:"要素の属性の値を取得する。"},
"dataset":{cat:"DOM",desc:"data-*属性にアクセスする。HTML側 data-id=\"5\" は el.dataset.id で読める。値は常に文字列。"},
"style":{cat:"DOM",desc:"要素のインラインスタイルをJSから操作する。el.style.color = \"red\"。プロパティ名はキャメルケース(backgroundColor)。"},
"value":{cat:"DOM",desc:"input/textarea/selectの入力値。読み取りも書き込みもできる。数値が欲しいときはNumber()で変換。"},
"checked":{cat:"DOM",desc:"チェックボックスやラジオボタンが選択されているか(true/false)。"},
"disabled":{cat:"DOM",desc:"ボタンや入力欄を無効化する属性/プロパティ。連打防止で送信中にtrueにするのが定番。"},
"focus":{cat:"DOM",desc:"要素にフォーカス(入力カーソル)を当てる。el.focus()。"},
"closest":{cat:"DOM",desc:"自分から親方向に遡って、セレクタに一致する最も近い要素を探す。イベント委譲とセットで頻出。"},
"parentElement":{cat:"DOM",desc:"自分の親要素。DOMツリーを上に辿るときに使う。"},
"children":{cat:"DOM",desc:"自分の直下の子要素の一覧。"},
"scrollIntoView":{cat:"DOM",desc:"その要素が見える位置までページをスクロールする。{behavior:\"smooth\"}でなめらかに。"},
"getBoundingClientRect":{cat:"DOM",desc:"要素の画面上の位置とサイズ(top/left/width/height)を取得する。位置計算の基本道具。"},
"NodeList":{cat:"DOM",desc:"querySelectorAllが返す「配列もどき」。forEachは使えるがmap等は不可。Array.from()で本物の配列にできる。"},
"DOM":{cat:"DOM",desc:"Document Object Model。HTMLの各要素をJavaScriptから操作できるようにした仕組み。"},
"window":{cat:"ブラウザ",desc:"ブラウザのウィンドウ全体を表す最上位オブジェクト。グローバル変数は実はwindowのプロパティ。"},
"alert":{cat:"ブラウザ",desc:"メッセージのポップアップを表示する。デバッグには便利だが、ユーザー体験的には多用しない。"},
"confirm":{cat:"ブラウザ",desc:"OK/キャンセルの確認ダイアログを出し、結果をtrue/falseで返す。"},
"prompt":{cat:"ブラウザ",desc:"文字入力付きのダイアログを出し、入力値を文字列で返す。キャンセル時はnull。"},
"location":{cat:"ブラウザ",desc:"現在のURL情報。location.href = \"...\"でページ移動、location.reload()で再読み込み。"},
"history":{cat:"ブラウザ",desc:"ブラウザの閲覧履歴を操作する。history.back()で戻る。SPAはpushStateでURLだけ書き換える。"},
"navigator":{cat:"ブラウザ",desc:"ブラウザ自体の情報や機能への入口。navigator.clipboard(コピー)、navigator.geolocation(位置情報)など。"},
"localStorage":{cat:"ブラウザ",desc:"ブラウザにデータを保存する仕組み。ページを閉じても消えない。文字列しか保存できないのでJSONと併用。"},
"sessionStorage":{cat:"ブラウザ",desc:"localStorageのタブを閉じたら消える版。一時的なデータ向け。"},
"setItem":{cat:"ブラウザ",desc:"localStorage.setItem(\"key\", 値)で保存する。値は文字列にする必要がある(JSON.stringifyとセット)。"},
"getItem":{cat:"ブラウザ",desc:"localStorage.getItem(\"key\")で読み出す。存在しないキーはnullが返る。"},
"removeItem":{cat:"ブラウザ",desc:"localStorageから指定キーのデータを削除する。"},
"console.log":{cat:"デバッグ",desc:"開発者ツールのコンソールに値を出力する。デバッグの基本道具。F12キーで確認できる。"},
"console.error":{cat:"デバッグ",desc:"エラーとしてコンソールに赤字で出力する。catchの中でよく使う。"},
"console.warn":{cat:"デバッグ",desc:"警告としてコンソールに黄色で出力する。"},
"console.table":{cat:"デバッグ",desc:"配列やオブジェクトを表形式で見やすく出力する。データ確認に便利。"},
"console":{cat:"デバッグ",desc:"開発者ツールのコンソールへの出力口。log/error/warn/tableなどを持つ。F12キーで開ける。"},
"debugger":{cat:"デバッグ",desc:"この行で実行を一時停止する命令。開発者ツールを開いた状態で動くと、その場で変数の中身を調べられる。"},
"breakpoint":{cat:"デバッグ",desc:"ブレークポイント。開発者ツールで指定した行で実行を止め、変数の状態を確認する機能。"},

/* ===== イベント ===== */
"event":{cat:"イベント",desc:"クリックや入力などの「出来事」の情報が詰まったオブジェクト。リスナー関数の第1引数で受け取る。"},
"click":{cat:"イベント",desc:"クリックされたときに発生するイベント。addEventListener(\"click\", ...)が最頻出。"},
"input":{cat:"イベント",desc:"入力欄の内容が変わるたびに発生するイベント。リアルタイム検索などに使う。"},
"change":{cat:"イベント",desc:"選択肢や入力の確定時に発生するイベント。selectやチェックボックスでよく使う。"},
"submit":{cat:"イベント",desc:"フォームが送信されたときに発生。preventDefault()でページ遷移を止めてJSで処理するのが定番。"},
"keydown":{cat:"イベント",desc:"キーが押されたときに発生。event.keyでどのキーか判定できる(\"Enter\"など)。"},
"load":{cat:"イベント",desc:"ページや画像の読み込みが完了したときに発生するイベント。"},
"DOMContentLoaded":{cat:"イベント",desc:"HTMLの解析が終わった時点で発生。画像を待たない分loadより早い。初期化処理の定番タイミング。"},
"preventDefault":{cat:"イベント",desc:"ブラウザの標準動作(フォーム送信でのページ遷移、リンク移動など)をキャンセルする。"},
"stopPropagation":{cat:"イベント",desc:"イベントが親要素へ伝わっていくの(バブリング)を止める。"},
"target":{cat:"イベント",desc:"event.target。イベントが実際に起きた要素。イベント委譲で「どれがクリックされたか」を知るのに使う。"},
"bubbling":{cat:"イベント",desc:"バブリング。子要素で起きたイベントが親、そのまた親へと伝わっていく仕組み。イベント委譲の土台。"},
"イベント委譲":{cat:"イベント",desc:"親要素に1つだけリスナーを付けて、子要素のイベントをまとめて処理するテクニック。動的に増える要素に強い。"},

/* ===== fetch・HTTP・API ===== */
"fetch":{cat:"HTTP",desc:"JavaScriptからHTTPリクエストを送る関数。await fetch(URL)の形で使い、外部APIとの連携はほぼこれ。"},
"response":{cat:"HTTP",desc:"fetchの結果(レスポンス)。response.ok で成功判定、response.json()で中身を取り出す。"},
"response.json":{cat:"HTTP",desc:"レスポンスの中身(JSON)をJavaScriptのオブジェクトに変換する。これもawaitが必要。"},
"response.ok":{cat:"HTTP",desc:"ステータスコードが200番台ならtrue。fetchは404でもエラーにならないので、この判定が大事。"},
"headers":{cat:"HTTP",desc:"リクエスト/レスポンスの付帯情報。Content-Type(データ形式)やAuthorization(認証)などを入れる。"},
"Content-Type":{cat:"HTTP",desc:"送るデータの形式を伝えるヘッダー。JSONなら\"application/json\"。"},
"Authorization":{cat:"HTTP",desc:"認証情報を載せるヘッダー。\"Bearer トークン\"の形式が定番。"},
"body":{cat:"HTTP",desc:"リクエストで送るデータ本体。JSONならJSON.stringify()した文字列を入れる。HTMLでは<body>タグの意味も。"},
"method":{cat:"HTTP",desc:"リクエストの種類。GET(取得)/POST(送信)/PUT・PATCH(更新)/DELETE(削除)。"},
"GET":{cat:"HTTP",desc:"「データをください」のリクエスト。ページ表示や検索。送るデータはURLに載る(?key=value)。"},
"POST":{cat:"HTTP",desc:"「データを送ります」のリクエスト。フォーム送信や新規作成。データはbodyに入れて送る。"},
"PUT":{cat:"HTTP",desc:"データ全体を置き換える更新リクエスト。"},
"PATCH":{cat:"HTTP",desc:"データの一部だけを更新するリクエスト。"},
"DELETE":{cat:"HTTP",desc:"データの削除を依頼するリクエスト。SQLのDELETE文とは別物(考え方は同じ)。"},
"HTTP":{cat:"HTTP",desc:"Webの通信の約束事。「リクエスト(お願い)→レスポンス(返事)」の繰り返しで成り立つ。"},
"HTTPS":{cat:"HTTP",desc:"HTTPの暗号化版。盗聴・改ざん・なりすましを防ぐ。データを送る先は必ずHTTPSにする。"},
"200":{cat:"ステータスコード",desc:"成功。リクエストが正常に処理された。"},
"201":{cat:"ステータスコード",desc:"作成成功。POSTで新しいデータが作られたときに返る。"},
"301":{cat:"ステータスコード",desc:"恒久的な引っ越し(リダイレクト)。URLが変わったことを示す。"},
"400":{cat:"ステータスコード",desc:"Bad Request。リクエストの内容が不正。送っているデータの形式を疑う。"},
"401":{cat:"ステータスコード",desc:"未認証。ログインやAPIキーが必要、または間違っている。"},
"403":{cat:"ステータスコード",desc:"アクセス禁止。認証は通っているが、その操作の権限がない。"},
"404":{cat:"ステータスコード",desc:"Not Found。そのURLに該当するものがない。URLのスペルミスが原因のことが多い。"},
"429":{cat:"ステータスコード",desc:"リクエストが多すぎる(レート制限)。時間を置いて再試行する。"},
"500":{cat:"ステータスコード",desc:"サーバー内部エラー。自分のリクエストでなく相手側の問題。400番台=こちら、500番台=あちら。"},
"503":{cat:"ステータスコード",desc:"サービス利用不可。サーバーが過負荷やメンテナンス中。"},
"API":{cat:"API",desc:"Application Programming Interface。プログラム同士が機能やデータをやり取りするための窓口・約束事。"},
"REST":{cat:"API",desc:"Web APIの設計スタイル。URLで対象を表し、HTTPメソッド(GET/POST等)で操作を表す。"},
"endpoint":{cat:"API",desc:"エンドポイント。APIの個々の窓口となるURL。/users や /orders など。"},
"CORS":{cat:"API",desc:"ブラウザが「別ドメインのAPIへのアクセス」を制限する仕組み。CORSエラーはサーバー側の許可設定で解決する。"},
"query parameter":{cat:"API",desc:"URLの?以降に付けるパラメータ(?page=2&sort=new)。個人情報を載せてはいけない(履歴やログに残る)。"},
"token":{cat:"API",desc:"認証の合言葉となる文字列。APIキーやアクセストークン。コードに直書きせず環境変数で管理する。"},
"JWT":{cat:"API",desc:"JSON Web Token。ユーザー情報を署名付きで詰めたトークン。ログイン状態の維持によく使われる。"},
"OAuth":{cat:"API",desc:"「Googleでログイン」のように、パスワードを渡さず他サービスに権限を許可する仕組み。"},
"webhook":{cat:"API",desc:"イベント発生時にサーバー側からこちらのURLへ通知してくれる仕組み。「向こうから来るAPI」。LINE Botなどで使う。"},
"rate limit":{cat:"API",desc:"レート制限。API の呼びすぎを防ぐ回数制限。超えると429エラー。リトライは間隔を空けて。"},
"URL":{cat:"Web",desc:"Webの住所。プロトコル(https)+ドメイン(example.com)+パス(/page)+クエリ(?a=1)で構成される。"},
"WebSocket":{cat:"Web",desc:"サーバーと双方向・リアルタイムに通信し続ける仕組み。チャットや通知などに使う。"},
"cookie":{cat:"Web",desc:"ブラウザに保存されサーバーへ自動送信される小さなデータ。ログイン状態の維持などに使われる。"},
"session":{cat:"Web",desc:"サーバー側でユーザーの状態を覚えておく仕組み。cookieのIDと紐づけて「ログイン中」を管理する。"},
"cache":{cat:"Web",desc:"キャッシュ。一度取得したデータを再利用して高速化する仕組み。「更新したのに変わらない」の原因にもなる。"},
"CDN":{cat:"Web",desc:"Contents Delivery Network。世界中のサーバーからファイルを配信する仕組み。ライブラリの読み込みにも使う。"},
"DNS":{cat:"Web",desc:"ドメイン名(example.com)をIPアドレスに変換する、インターネットの電話帳。"},
"SSL/TLS":{cat:"Web",desc:"通信を暗号化するプロトコル。HTTPSの中身。証明書の期限切れはサイト警告の定番原因。"},

/* ===== HTML ===== */
"div":{cat:"HTML",desc:"汎用の箱(ブロック要素)。レイアウトのグループ化に使う。意味は持たない。"},
"span":{cat:"HTML",desc:"汎用のインライン要素。文中の一部分にだけスタイルを当てたいときに使う。"},
"p":{cat:"HTML",desc:"段落(paragraph)。文章のまとまりを表す。"},
"a":{cat:"HTML",desc:"リンク(anchor)。href属性で飛び先を指定する。target=\"_blank\"で新しいタブに開く。"},
"img":{cat:"HTML",desc:"画像。src属性でファイルを指定。alt属性(代替テキスト)はアクセシビリティのため必ず書く。"},
"ul":{cat:"HTML",desc:"順序なしリスト(・付きの箇条書き)。中にはliを入れる。"},
"ol":{cat:"HTML",desc:"順序ありリスト(番号付きの箇条書き)。"},
"li":{cat:"HTML",desc:"リストの1項目。ulまたはolの中に入れる。"},
"table":{cat:"HTML",desc:"表。tr(行)→ th/td(セル)の入れ子で作る。"},
"tr":{cat:"HTML",desc:"表の1行(table row)。"},
"td":{cat:"HTML",desc:"表のデータセル(table data)。"},
"th":{cat:"HTML",desc:"表の見出しセル(table header)。"},
"form":{cat:"HTML",desc:"入力フォームのまとまり。submitイベントで送信を検知できる。"},
"textarea":{cat:"HTML",desc:"複数行の文字入力欄。値は.valueで取得する。"},
"button":{cat:"HTML",desc:"ボタン。form内ではtype=\"button\"を付けないと勝手に送信ボタンになるので注意。"},
"select":{cat:"HTML",desc:"プルダウン(選択肢)。中にoptionを入れる。選ばれた値は.valueで取れる。"},
"option":{cat:"HTML",desc:"selectの中の選択肢1つ。value属性が実際の値、タグの中身が表示名。"},
"label":{cat:"HTML",desc:"入力欄のラベル。for属性で入力欄と紐づけるとクリックでフォーカスが移る。"},
"h1":{cat:"HTML",desc:"最上位の見出し。ページに1つが基本。h1〜h6まで段階がある。"},
"h2":{cat:"HTML",desc:"2番目のレベルの見出し。セクションの表題に使う。"},
"h3":{cat:"HTML",desc:"3番目のレベルの見出し。"},
"header":{cat:"HTML",desc:"ページやセクションの頭部を表す意味づけタグ。ロゴやナビを入れることが多い。"},
"footer":{cat:"HTML",desc:"ページやセクションの末尾を表す意味づけタグ。"},
"nav":{cat:"HTML",desc:"ナビゲーション(メニュー)を表す意味づけタグ。"},
"main":{cat:"HTML",desc:"ページの主要コンテンツを表す意味づけタグ。ページに1つ。"},
"section":{cat:"HTML",desc:"意味のあるまとまり(章・節)を表すタグ。見出しとセットで使う。"},
"article":{cat:"HTML",desc:"単体で完結する記事・投稿を表すタグ。"},
"script":{cat:"HTML",desc:"JavaScriptを書く/読み込むタグ。src属性で外部ファイルも読み込める。"},
"link":{cat:"HTML",desc:"外部リソース(主にCSS)を読み込むタグ。<link rel=\"stylesheet\" href=\"...\">。"},
"meta":{cat:"HTML",desc:"ページの付帯情報。charset(文字コード)やviewport(スマホ表示設定)などを指定する。"},
"head":{cat:"HTML",desc:"ページの設定部分。タイトル、CSS読み込み、メタ情報などを書く。画面には表示されない。"},
"canvas":{cat:"HTML",desc:"JavaScriptで図形や画像を自由に描画できる領域。ゲームやグラフ、画像処理に使う。"},
"video":{cat:"HTML",desc:"動画を埋め込むタグ。controls属性で再生ボタンが付く。"},
"iframe":{cat:"HTML",desc:"ページの中に別のページを埋め込むタグ。YouTube埋め込みなどで見かける。"},
"input":{cat:"HTML",desc:"1行の入力欄。type属性でtext/number/date/checkbox/radioなど姿が変わる。JSではinputイベントの意味も。"},
"placeholder":{cat:"HTML",desc:"入力欄が空のときに薄く表示されるヒント文字。"},
"required":{cat:"HTML",desc:"入力必須にする属性。ブラウザが送信時に自動チェックしてくれる。"},
"href":{cat:"HTML",desc:"リンクの飛び先URLを指定する属性。<a href=\"...\">。"},
"src":{cat:"HTML",desc:"画像やスクリプトなどの読み込み元を指定する属性。<img src=\"...\">。"},
"alt":{cat:"HTML",desc:"画像が表示できないときの代替テキスト。スクリーンリーダーも読み上げる。"},
"id":{cat:"HTML",desc:"要素につける一意の名前。ページ内で重複してはいけない。JSからgetElementByIdで取得できる。"},
"attribute":{cat:"HTML",desc:"属性。タグに付ける追加情報(id、class、srcなど)。名前=\"値\"の形で書く。"},
"semantic":{cat:"HTML",desc:"セマンティックHTML。divだけでなくheader/nav/mainなど意味のあるタグを使う書き方。検索や支援技術に優しい。"},

/* ===== CSS ===== */
"display":{cat:"CSS",desc:"要素の表示方式。block(縦積み)/inline(文中)/flex/grid/none(非表示)など。レイアウトの起点。"},
"flex":{cat:"CSS",desc:"display:flex。子要素を柔軟に並べるレイアウト。横並び・中央寄せ・均等配置が簡単にできる。"},
"grid":{cat:"CSS",desc:"display:grid。行と列の格子でレイアウトする方式。カード一覧など2次元配置に強い。"},
"justify-content":{cat:"CSS",desc:"flex/gridの主軸方向(通常は横)の配置。center(中央)、space-between(両端揃え)など。"},
"align-items":{cat:"CSS",desc:"flex/gridの交差軸方向(通常は縦)の配置。centerで縦中央揃え。"},
"gap":{cat:"CSS",desc:"flex/gridの子要素間の隙間。marginを個別に付けるよりきれいに書ける。"},
"position":{cat:"CSS",desc:"要素の配置方法。static(通常)/relative(相対)/absolute(絶対)/fixed(画面固定)/sticky(スクロール追従)。"},
"absolute":{cat:"CSS",desc:"position:absolute。親(position指定あり)を基準にtop/leftで自由な位置に置く。"},
"relative":{cat:"CSS",desc:"position:relative。通常位置を基準に少しずらす。absoluteの子の基準点にもなる。"},
"fixed":{cat:"CSS",desc:"position:fixed。スクロールしても画面の同じ位置に固定される。ヘッダーやツールチップに使う。"},
"sticky":{cat:"CSS",desc:"position:sticky。スクロールで指定位置に達すると貼り付く。追従する見出しなどに。"},
"margin":{cat:"CSS",desc:"要素の外側の余白。margin: 0 auto;で左右中央寄せの定番技。"},
"padding":{cat:"CSS",desc:"要素の内側の余白(枠と中身の間)。"},
"border":{cat:"CSS",desc:"要素の枠線。border: 1px solid #ccc; のように太さ・種類・色で指定。"},
"border-radius":{cat:"CSS",desc:"角を丸くする。50%で正円になる。"},
"background":{cat:"CSS",desc:"背景。色(background-color)、画像、グラデーションなどをまとめて指定できる。"},
"color":{cat:"CSS",desc:"文字色。#20293Aのような16進数、rgb()、色名で指定する。"},
"font-size":{cat:"CSS",desc:"文字の大きさ。px(固定)やrem(ルート基準の相対値)で指定する。"},
"font-family":{cat:"CSS",desc:"フォントの種類。候補をカンマ区切りで並べ、先頭から順に使われる。"},
"font-weight":{cat:"CSS",desc:"文字の太さ。400が標準、700がbold。"},
"line-height":{cat:"CSS",desc:"行の高さ(行間)。1.5〜1.8くらいが読みやすい目安。"},
"width":{cat:"CSS",desc:"要素の幅。%は親要素基準。max-widthと組み合わせて画面サイズに対応する。"},
"height":{cat:"CSS",desc:"要素の高さ。100vhで画面の高さいっぱい。"},
"max-width":{cat:"CSS",desc:"幅の上限。本文をmax-width:800px等にすると大画面でも読みやすい。"},
"overflow":{cat:"CSS",desc:"中身がはみ出たときの扱い。hidden(隠す)/scroll(スクロール)/auto(必要ならスクロール)。"},
"z-index":{cat:"CSS",desc:"重なり順。数字が大きいほど手前。position指定がある要素にだけ効く。"},
"opacity":{cat:"CSS",desc:"不透明度。1が完全表示、0が透明。フェードの演出に使う。"},
"transition":{cat:"CSS",desc:"プロパティの変化をなめらかにする。transition: .3s; でホバー時の色変化などがアニメーションになる。"},
"transform":{cat:"CSS",desc:"要素を変形する。translate(移動)、scale(拡縮)、rotate(回転)。アニメーションと相性がよい。"},
"animation":{cat:"CSS",desc:"@keyframesで定義した動きを要素に適用する。ローディングのくるくる等。"},
"hover":{cat:"CSS",desc:":hover擬似クラス。マウスをのせたときのスタイルを指定する。button:hover{...}。"},
"media":{cat:"CSS",desc:"@media(メディアクエリ)。画面幅などの条件でスタイルを切り替える。レスポンシブ対応の中核。"},
"rem":{cat:"CSS",desc:"ルート要素(html)のfont-size基準の単位。1rem=通常16px。拡大設定に追従するのでpxより柔軟。"},
"em":{cat:"CSS",desc:"親要素のfont-size基準の単位。入れ子で倍々になるので注意。HTMLでは強調タグ<em>の意味も。"},
"px":{cat:"CSS",desc:"ピクセル。固定サイズの単位。"},
"vh":{cat:"CSS",desc:"画面の高さの1%。100vhで画面いっぱいの高さ。"},
"vw":{cat:"CSS",desc:"画面の幅の1%。"},
"box-sizing":{cat:"CSS",desc:"widthにpadding/borderを含めるかの設定。border-boxにすると直感的になり、*{box-sizing:border-box}が定番。"},
"cursor":{cat:"CSS",desc:"マウスカーソルの形。pointerで指マーク(クリックできる感)になる。"},
"var(--)":{cat:"CSS",desc:"CSS変数。:rootで--main-color:#333;と定義し、var(--main-color)で使い回す。テーマ変更が楽になる。"},
"calc":{cat:"CSS",desc:"CSS内で計算する。width: calc(100% - 80px); のように単位をまたいだ計算ができる。"},
"selector":{cat:"CSS",desc:"セレクタ。どの要素にスタイルを当てるかの指定。.class、#id、タグ名、組み合わせ(div > p)など。"},
"specificity":{cat:"CSS",desc:"詳細度。セレクタの強さの優先順位。id > class > タグ。「スタイルが効かない」の原因の定番。"},
"responsive":{cat:"CSS",desc:"レスポンシブデザイン。画面サイズに応じてレイアウトが変わる作り。メディアクエリとflex/gridで実現する。"},
"Tailwind":{cat:"CSS",desc:"Tailwind CSS。class=\"p-4 text-lg\"のように小さなユーティリティclassを組み合わせるCSSフレームワーク。"},

/* ===== エラー ===== */
"TypeError":{cat:"エラー",desc:"型が想定と違う操作をした。「Cannot read properties of undefined」は中身が空のものからプロパティを読んだ意味。"},
"ReferenceError":{cat:"エラー",desc:"存在しない変数を使った。「is not defined」= 変数名のスペルミスか、定義前に使ったケースが多い。"},
"SyntaxError":{cat:"エラー",desc:"書き方の間違い。括弧の閉じ忘れ、カンマ忘れなど。エラー行の前後をよく見る。"},
"RangeError":{cat:"エラー",desc:"値が許容範囲外。無限再帰による「Maximum call stack size exceeded」もこの仲間。"},
"NetworkError":{cat:"エラー",desc:"通信の失敗。URL間違い、サーバーダウン、CORS制限などが原因。"},
"Uncaught":{cat:"エラー",desc:"「キャッチされていない」エラー。try/catchで受け止められずコンソールに出たもの。行番号が手がかり。"},
"undefined is not a function":{cat:"エラー",desc:"関数でないものを関数として呼んだ。メソッド名のスペルミスが定番原因。"},
"stack trace":{cat:"エラー",desc:"スタックトレース。エラーに至るまでの関数呼び出しの経路。上から順に「どこから呼ばれたか」を辿れる。"},
"exception":{cat:"エラー",desc:"例外。実行中に起きるエラーのこと。throwで投げ、try/catchで受け止める。"},

/* ===== セキュリティ ===== */
"XSS":{cat:"セキュリティ",desc:"クロスサイトスクリプティング。ユーザー入力をそのままHTMLに埋め込むと悪意あるスクリプトが実行される脆弱性。対策はエスケープとtextContent。"},
"SQLインジェクション":{cat:"セキュリティ",desc:"入力をSQL文に文字列連結すると想定外の命令を実行される脆弱性。対策はプレースホルダ(パラメータ化クエリ)。"},
"CSRF":{cat:"セキュリティ",desc:"ログイン中のユーザーに意図しないリクエストを送らせる攻撃。対策はCSRFトークンやSameSite Cookie。"},
"escape":{cat:"セキュリティ",desc:"エスケープ。<を&lt;に変えるなど、特別な意味を持つ文字を無害化すること。表示前の必須処理。"},
"sanitize":{cat:"セキュリティ",desc:"サニタイズ。入力から危険な部分を除去・無害化すること。"},
"validation":{cat:"セキュリティ",desc:"バリデーション。入力値の検証。型・範囲・必須・長さをチェックする。本当の守りはサーバー側で行う。"},
"encrypt":{cat:"セキュリティ",desc:"暗号化。鍵があれば元に戻せる変換。通信(HTTPS)やデータ保管に使う。"},
"hash":{cat:"セキュリティ",desc:"ハッシュ化。元に戻せない一方向の変換。パスワードは暗号化でなくハッシュ化して保存する。"},
"salt":{cat:"セキュリティ",desc:"ソルト。ハッシュ化の前に付け足すランダム文字列。同じパスワードでも違うハッシュになり、解析に強くなる。"},
"APIキー":{cat:"セキュリティ",desc:"APIを使うための合言葉。コードに直書きしてGitHubに公開すると漏洩事故。環境変数+.gitignoreで管理する。"},
"env":{cat:"セキュリティ",desc:".envファイル。APIキーなどの秘密情報を書く場所。必ず.gitignoreに登録してGit管理から外す。"},
"環境変数":{cat:"セキュリティ",desc:"OSやサーバー側に持たせる設定値。秘密情報をコードから分離する基本手段。process.env.KEY等で読む。"},
"認証":{cat:"セキュリティ",desc:"Authentication。「この人が誰か」の確認。ログインが代表例。認可(何ができるか)とセットで考える。"},
"認可":{cat:"セキュリティ",desc:"Authorization。「その人に何を許すか」の確認。認証だけで認可を忘れると他人のデータが見える事故になる。"},
"IDOR":{cat:"セキュリティ",desc:"URLのIDを変えるだけで他人のデータにアクセスできてしまう脆弱性。認可チェック漏れが原因。"},
"CSP":{cat:"セキュリティ",desc:"Content Security Policy。読み込みを許可するスクリプト等をヘッダーで宣言し、XSSの被害を抑える仕組み。"},

/* ===== Git・開発ツール ===== */
"git":{cat:"Git",desc:"コードの変更履歴を管理するツール。「いつ誰が何を変えたか」を記録し、いつでも戻れる。"},
"commit":{cat:"Git",desc:"変更履歴の1単位として記録すること。「意味のあるまとまり+わかるメッセージ」が基本。"},
"push":{cat:"Git",desc:"ローカルのコミットをGitHubなどのリモートに送る。"},
"pull":{cat:"Git",desc:"リモートの最新の変更をローカルに取り込む。"},
"clone":{cat:"Git",desc:"リモートのリポジトリを丸ごとローカルに複製する。開発参加の最初の一歩。"},
"branch":{cat:"Git",desc:"ブランチ。履歴の枝分かれ。本流(main)を守りつつ、別の枝で安全に開発できる。"},
"merge":{cat:"Git",desc:"ブランチの変更を別のブランチに合流させる。同じ箇所を変更しているとコンフリクトが起きる。"},
"conflict":{cat:"Git",desc:"コンフリクト(衝突)。同じ箇所を別々に変更してマージできない状態。手動でどちらを採用するか選んで解決する。"},
"repository":{cat:"Git",desc:"リポジトリ。プロジェクトのファイルと変更履歴の保管庫。GitHub上のものをリモートリポジトリと呼ぶ。"},
"gitignore":{cat:"Git",desc:".gitignore。Git管理から除外するファイルの一覧。node_modulesや.env(秘密情報)は必ず登録する。"},
"pull request":{cat:"Git",desc:"PR。「この変更を取り込んで」という提案。レビューを受けてからマージするチーム開発の要。"},
"GitHub":{cat:"Git",desc:"Gitリポジトリのホスティングサービス。共有・レビュー・公開(GitHub Pages)までできる開発の拠点。"},
"npm":{cat:"開発ツール",desc:"Node.jsのパッケージ管理ツール。npm installでライブラリ導入、npm runでスクリプト実行。"},
"npm install":{cat:"開発ツール",desc:"package.jsonに書かれた依存ライブラリを一括インストールする。プロジェクトを動かす最初のコマンド。"},
"npm audit":{cat:"開発ツール",desc:"使用中のライブラリに既知の脆弱性がないか照合するコマンド。定期的に実行する習慣を。"},
"npx":{cat:"開発ツール",desc:"パッケージをインストールせずその場で実行する。npx serve でお試しサーバー起動など。"},
"Node.js":{cat:"開発ツール",desc:"ブラウザの外(PC・サーバー)でJavaScriptを動かす実行環境。サーバーやビルドツールの土台。"},
"node_modules":{cat:"開発ツール",desc:"npmでインストールしたライブラリの置き場。巨大なのでGit管理には含めない(.gitignore対象)。"},
"package.json":{cat:"開発ツール",desc:"プロジェクトの設定ファイル。使用ライブラリ(dependencies)や実行スクリプト(scripts)が書かれている。"},
"dependencies":{cat:"開発ツール",desc:"アプリの動作に必要なライブラリ一覧。devDependenciesは開発時のみ必要なもの。"},
"CLI":{cat:"開発ツール",desc:"Command Line Interface。文字入力で操作する画面(ターミナル)。git、npmなど開発ツールの多くはCLI。"},
"IDE":{cat:"開発ツール",desc:"統合開発環境。エディタ+デバッグ+補完が一体になったツール。VSCodeが代表格。"},
"linter":{cat:"開発ツール",desc:"コードの問題(未使用変数、書式ゆれ等)を自動検出するツール。ESLintが定番。"},
"formatter":{cat:"開発ツール",desc:"コードの見た目(インデント等)を自動整形するツール。Prettierが定番。"},
"Vite":{cat:"開発ツール",desc:"高速なフロントエンド開発ツール。開発サーバー(npm run dev)とビルド(npm run build)を担う。"},
"build":{cat:"開発ツール",desc:"ビルド。開発用コードを本番配布用に変換・圧縮すること。成果物(dist等)は直接編集しない。"},
"deploy":{cat:"開発ツール",desc:"デプロイ。作ったアプリをサーバーに配置して公開すること。VercelやGitHub Pagesなら数分でできる。"},
"localhost":{cat:"開発ツール",desc:"自分のPC自身を指すアドレス。http://localhost:3000は「自分のPCの3000番ポート」。"},
"port":{cat:"開発ツール",desc:"ポート番号。1台のマシンで複数のサーバーを区別する番号。URLの:3000の部分。"},
"terminal":{cat:"開発ツール",desc:"ターミナル。コマンドを打ち込んでPCを操作する画面。開発の基本インターフェース。"},
"docker":{cat:"開発ツール",desc:"アプリを環境ごとコンテナに詰めて、どこでも同じように動かすツール。「自分のPCでは動くのに」問題の解決策。"},

/* ===== フレームワーク・ライブラリ ===== */
"library":{cat:"概念",desc:"ライブラリ。よく使う機能を部品化した他人のコード。呼び出して使う。"},
"framework":{cat:"概念",desc:"フレームワーク。アプリの骨組みを提供する仕組み。こちらのコードが枠組みに沿って呼ばれる点がライブラリと逆。"},
"React":{cat:"フレームワーク",desc:"UIをコンポーネント(部品)の組み合わせで作るライブラリ。データが変わると画面が自動で更新される。"},
"Vue":{cat:"フレームワーク",desc:"Reactと並ぶUIフレームワーク。HTMLに近い書き心地で学びやすいと言われる。"},
"component":{cat:"フレームワーク",desc:"コンポーネント。UIの再利用可能な部品。ボタンやカードを部品化して組み合わせてページを作る。"},
"props":{cat:"フレームワーク",desc:"親コンポーネントから子へ渡すデータ。関数の引数のようなもの。子からは変更しない。"},
"state":{cat:"フレームワーク",desc:"コンポーネントが持つ「変わりうるデータ」。stateが変わると画面が自動で再描画される。"},
"useState":{cat:"フレームワーク",desc:"Reactでstateを作るフック。const [count, setCount] = useState(0); の形。値の変更は必ずsetCount経由。"},
"useEffect":{cat:"フレームワーク",desc:"Reactで「描画後に実行する処理」(データ取得など)を書くフック。第2引数の依存配列が挙動の鍵。"},
"hook":{cat:"フレームワーク",desc:"フック。Reactの関数コンポーネントに状態や機能を追加する仕組み。useで始まる関数。"},
"JSX":{cat:"フレームワーク",desc:"JavaScriptの中にHTMLのような記法を書くReactの構文。{ }の中にJSの式を埋め込める。"},
"TypeScript":{cat:"言語",desc:"JavaScriptに型を追加した言語。実行前に型の食い違いを検出でき、大きなアプリで威力を発揮する。"},
"型注釈":{cat:"言語",desc:"TypeScriptで変数や引数の型を明示する書き方。let age: number = 6; のコロン以降。"},
"interface":{cat:"言語",desc:"TypeScriptでオブジェクトの形(どんなキーと型を持つか)を定義する。型の設計図。"},
"jQuery":{cat:"フレームワーク",desc:"かつての定番DOM操作ライブラリ。$(\"#id\")の記法。今は素のJSで大体できるため新規採用は減少。"},

/* ===== SQL・データベース ===== */
"SQL":{cat:"SQL",desc:"データベースを操作する言語。SELECT(取得)/INSERT(追加)/UPDATE(更新)/DELETE(削除)が基本4操作。"},
"SELECT":{cat:"SQL",desc:"データを取得する命令。SELECT 列名 FROM テーブル WHERE 条件; の形。*は全列。"},
"INSERT":{cat:"SQL",desc:"データを追加する命令。INSERT INTO テーブル (列) VALUES (値);。"},
"UPDATE":{cat:"SQL",desc:"データを更新する命令。WHEREを忘れると全行が書き換わる大事故になるので要注意。"},
"WHERE":{cat:"SQL",desc:"対象の行を絞り込む条件。UPDATE/DELETEでは必須級。忘れると全行に適用される。"},
"FROM":{cat:"SQL",desc:"どのテーブルからデータを取るかの指定。"},
"JOIN":{cat:"SQL",desc:"複数のテーブルを共通のキーで結合して取得する。INNER JOIN(両方にある行)、LEFT JOIN(左は全部)など。"},
"ORDER BY":{cat:"SQL",desc:"結果の並び順を指定する。ASC(昇順)/DESC(降順)。"},
"GROUP BY":{cat:"SQL",desc:"同じ値の行をまとめて集計する。COUNTやSUMとセットで使う。"},
"LIMIT":{cat:"SQL",desc:"取得する行数の上限。大量データを全部取らないための基本マナー。"},
"PRIMARY KEY":{cat:"SQL",desc:"主キー。行を一意に特定する列。重複・NULL不可。idという名前が定番。"},
"FOREIGN KEY":{cat:"SQL",desc:"外部キー。別テーブルの主キーを参照する列。テーブル同士の関係を表す。"},
"index":{cat:"SQL",desc:"インデックス。検索を高速にする索引。本の索引と同じ発想。JSでは配列の位置番号の意味も。"},
"NULL":{cat:"SQL",desc:"SQLでの「値なし」。比較は = でなく IS NULL を使う点に注意。"},
"database":{cat:"SQL",desc:"データベース。データを整理して保管し、検索・更新できるようにした仕組み。RDB(表形式)が主流。"},
"NoSQL":{cat:"SQL",desc:"表形式でないデータベースの総称。JSONのような形で保存するMongoDB、キー値のRedisなど。"},

/* ===== Python ===== */
"def":{cat:"Python",desc:"Pythonで関数を定義するキーワード。def greet(name): の形。ブロックはインデントで表す。"},
"print":{cat:"Python",desc:"Pythonで値を画面に出力する関数。JSのconsole.logにあたるデバッグの基本。"},
"elif":{cat:"Python",desc:"Pythonの「else if」。if / elif / else で条件分岐を重ねる。"},
"lambda":{cat:"Python",desc:"Pythonの無名関数。lambda x: x * 2。JSのアロー関数にあたる。"},
"self":{cat:"Python",desc:"Pythonのクラスで「インスタンス自身」を指す。メソッドの第1引数に必ず書く。JSのthisにあたる。"},
"None":{cat:"Python",desc:"Pythonの「値なし」。JSのnullにあたる。判定は is None を使う。"},
"range":{cat:"Python",desc:"連続した数値の並びを作る。for i in range(5): で0〜4のループ。"},
"len":{cat:"Python",desc:"Pythonで長さ(要素数・文字数)を返す関数。len([1,2,3]) → 3。JSの.lengthにあたる。"},
"dict":{cat:"Python",desc:"Pythonの辞書型。{\"key\": \"value\"}の形。JSのオブジェクトにあたる。"},
"list":{cat:"Python",desc:"Pythonのリスト型。[1, 2, 3]の形。JSの配列にあたる。"},
"tuple":{cat:"Python",desc:"Pythonの変更できないリスト。(1, 2)の形。"},
"f-string":{cat:"Python",desc:"Pythonの文字列補間。f\"こんにちは{name}\" の形。JSのテンプレート文字列にあたる。"},
"pip":{cat:"Python",desc:"Pythonのパッケージ管理ツール。pip install ライブラリ名。JSのnpmにあたる。"},
"import(Python)":{cat:"Python",desc:"Pythonでライブラリを読み込む。import pandas as pd のようにasで別名を付けるのが定番。"},
"pandas":{cat:"Python",desc:"表データ(Excel/CSV的なもの)を扱うPythonの定番ライブラリ。データ分析・業務効率化の主戦力。"},
"indent":{cat:"Python",desc:"インデント(字下げ)。Pythonでは見た目でなく文法。ズレるとIndentationErrorになる。"},

/* ===== AI・LLM ===== */
"LLM":{cat:"AI",desc:"大規模言語モデル。ChatGPTやClaudeの中身。文章の続きを予測する仕組みで会話や生成を行う。"},
"prompt":{cat:"AI",desc:"プロンプト。AIへの指示文。役割・出力形式・例・制約を書くと出力が安定する。"},
"system prompt":{cat:"AI",desc:"会話全体の前提をAIに与える指示。「あなたは〜の講師です」など。ユーザーの発言とは別枠で渡す。"},
"messages":{cat:"AI",desc:"AI APIに渡す会話履歴の配列。role(user/assistant)とcontentのペア。毎回全部送るのが基本。"},
"role":{cat:"AI",desc:"messagesの発言者区分。user=人間、assistant=AI、system=前提指示。"},
"max_tokens":{cat:"AI",desc:"AIの返答の長さの上限。トークンは単語より細かい単位で、日本語は1文字1〜2トークン程度。"},
"token(AI)":{cat:"AI",desc:"AIが文章を処理する最小単位。API料金や文字数制限はトークン数で数えられる。"},
"temperature":{cat:"AI",desc:"AIの出力のランダムさ。低いと堅実で毎回似た答え、高いと多様で創造的になる。"},
"hallucination":{cat:"AI",desc:"ハルシネーション。AIがもっともらしい嘘を出力すること。AI出力は必ず検証する前提で使う。"},
"RAG":{cat:"AI",desc:"検索拡張生成。質問に関連する自社データ等を検索してAIに渡し、根拠のある回答をさせる構成。"},
"fine-tuning":{cat:"AI",desc:"ファインチューニング。既存のAIモデルを自分のデータで追加学習させること。"},
"MCP":{cat:"AI",desc:"Model Context Protocol。AIに外部ツールやデータへの接続口を standard な形で生やす仕組み。"},

/* ===== 演算子・記号 ===== */
"=>":{cat:"演算子",desc:"アロー関数。(引数) => 処理 の形で関数を書く記法。functionの短縮形で、今の主流。"},
"===":{cat:"演算子",desc:"厳密等価。型も値も同じならtrue。比較は基本これを使う(==は型変換が起きて事故のもと)。"},
"!==":{cat:"演算子",desc:"厳密不等価。型か値が違えばtrue。"},
"==":{cat:"演算子",desc:"等価(緩い比較)。\"3\" == 3 がtrueになるなど型変換が起きる。基本は===を使う。"},
"&&":{cat:"演算子",desc:"AND(かつ)。両方trueならtrue。a && b は「aが真ならbを返す」ので条件付き実行にも使われる。"},
"||":{cat:"演算子",desc:"OR(または)。どちらかがtrueならtrue。a || b は「aが偽ならbを返す」のでデフォルト値にも使われる。"},
"!":{cat:"演算子",desc:"NOT(否定)。trueをfalseに、falseをtrueに反転する。!!値 で真偽値への変換になる。"},
"??":{cat:"演算子",desc:"null合体演算子。左がnull/undefinedのときだけ右を使う。0や\"\"を有効値として扱える点で||より安全。"},
"?.":{cat:"演算子",desc:"オプショナルチェーン。obj?.name は objがnull/undefinedでもエラーにならずundefinedを返す。"},
"...":{cat:"演算子",desc:"スプレッド構文/残余引数。配列やオブジェクトの展開([...arr])、可変長引数(...args)に使う。"},
"++":{cat:"演算子",desc:"インクリメント。変数を1増やす。i++ はループの更新部の定番。"},
"--":{cat:"演算子",desc:"デクリメント。変数を1減らす。"},
"+=":{cat:"演算子",desc:"加算代入。a += 2 は a = a + 2 の短縮形。文字列の連結にも使える。"},
"%":{cat:"演算子",desc:"剰余(あまり)。10 % 3 → 1。偶数判定(n % 2 === 0)や周期処理で頻出。"},
"**":{cat:"演算子",desc:"べき乗。2 ** 10 → 1024。"},
"?:":{cat:"演算子",desc:"三項演算子。条件 ? 真のとき : 偽のとき。短いif/elseを1行で書ける。"},
"${}":{cat:"演算子",desc:"テンプレート文字列の埋め込み口。`こんにちは${name}` のようにバッククォート内で変数を展開する。"},
"//":{cat:"記号",desc:"1行コメント。//以降は実行されないメモ。「なぜこうしたか」を書くのが良いコメント。"},
"/* */":{cat:"記号",desc:"複数行コメント。/*から*/までが実行されないメモになる。"},
"=":{cat:"演算子",desc:"代入。右の値を左の変数に入れる。「等しい」の比較は===なので混同注意。"},

/* ===== 一般概念 ===== */
"algorithm":{cat:"概念",desc:"アルゴリズム。問題を解く手順のこと。同じ結果でも手順の良し悪しで速度が大きく変わる。"},
"refactoring":{cat:"概念",desc:"リファクタリング。動作を変えずにコードを読みやすく整理すること。「動くからOK」の次の一歩。"},
"DRY":{cat:"概念",desc:"Don't Repeat Yourself。同じコードを繰り返し書かない原則。繰り返しは関数化・部品化する。"},
"モジュール化":{cat:"概念",desc:"処理を「1つの関数は1つの仕事」に分けること。デバッグとAIへの指示が一気に楽になる。"},
"recursion":{cat:"概念",desc:"再帰。関数が自分自身を呼び出すこと。終了条件を忘れるとスタックオーバーフローになる。"},
"immutable":{cat:"概念",desc:"不変。作った後に変更しないデータの扱い方。元を変えずコピーを作る(map/filter/スプレッド)のが現代の主流。"},
"side effect":{cat:"概念",desc:"副作用。関数が戻り値以外に外部の状態(画面、ファイル、グローバル変数)を変えること。少ないほど追いやすい。"},
"pure function":{cat:"概念",desc:"純粋関数。同じ入力なら必ず同じ出力で、副作用がない関数。テストしやすくバグりにくい。"},
"SPA":{cat:"概念",desc:"Single Page Application。ページ遷移せずJSで画面を書き換えるWebアプリ。React製アプリの多くがこれ。"},
"frontend":{cat:"概念",desc:"フロントエンド。ブラウザで動く画面側(HTML/CSS/JS)。ユーザーから丸見えなので秘密情報は置けない。"},
"backend":{cat:"概念",desc:"バックエンド。サーバー側の処理。DB操作、認証、APIキーを使う処理はここに置く。"},
"server":{cat:"概念",desc:"サーバー。リクエストを受けてレスポンスを返すコンピュータ/プログラム。"},
"client":{cat:"概念",desc:"クライアント。サーバーにリクエストを送る側。ブラウザやスマホアプリ。"},
"runtime":{cat:"概念",desc:"ランタイム。プログラムの実行環境。同じJSでもブラウザとNode.jsでは使える機能が違う。"},
"compile":{cat:"概念",desc:"コンパイル。人間が書いたコードを機械が実行できる形に変換すること。TypeScript→JSの変換もこの仲間。"},
"変換(キャスト)":{cat:"概念",desc:"型変換。Number(\"3\")、String(3)のように型を変えること。暗黙の型変換はバグの温床。"},
"queue":{cat:"概念",desc:"キュー。先入れ先出し(FIFO)のデータ構造。行列と同じで、先に並んだものから処理される。"},
"stack":{cat:"概念",desc:"スタック。後入れ先出し(LIFO)のデータ構造。関数呼び出しの管理(コールスタック)にも使われる。"},
"O(n)":{cat:"概念",desc:"計算量の表記(オーダー)。データ量nに比例して処理時間が伸びる意味。O(n²)はnの2乗で遅くなる。"},
"regex":{cat:"概念",desc:"正規表現。文字列のパターンを表す記法。\\d(数字)、+(1回以上)、*(0回以上)、^(先頭)、$(末尾)など。"},
"UTF-8":{cat:"概念",desc:"文字コードの世界標準。文字化けの多くは文字コードの不一致が原因。<meta charset=\"UTF-8\">で宣言する。"},
"CSV":{cat:"概念",desc:"カンマ区切りのテキストデータ形式。Excelとプログラムの橋渡しでよく使う。"},
"Markdown":{cat:"概念",desc:"# 見出し、- 箇条書きなど記号で書ける文書記法。READMEやドキュメントの標準。"},
"README":{cat:"概念",desc:"プロジェクトの説明書。何のためのものか、どう動かすかを最初に読む人向けに書く。"},
"pseudocode":{cat:"概念",desc:"擬似コード。実際の文法にとらわれず日本語まじりで処理の流れを書いたもの。設計の下書きに便利。"}
};
